{{- if .Values.podDisruptionBudget.backend.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kube-guard.fullname" . }}-backend
  labels:
    {{- include "kube-guard.backend.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.backend.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.backend.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.backend.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.backend.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kube-guard.backend.selectorLabels" . | nindent 6 }}
{{- end }}
---
{{- if .Values.podDisruptionBudget.frontend.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kube-guard.fullname" . }}-frontend
  labels:
    {{- include "kube-guard.frontend.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.frontend.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.frontend.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.frontend.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.frontend.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kube-guard.frontend.selectorLabels" . | nindent 6 }}
{{- end }}
