apiVersion: kube-guard.io/v1alpha1
kind: ScanRequest
metadata:
  name: wordpress-scan
  namespace: kube-guard
spec:
  source:
    repo: https://github.com/bitnami/charts.git
    path: bitnami/wordpress
    ref: main
  scanners:
    - trivy
  render:
    type: helm
