apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helmscanreports.kube-guard.io
spec:
  group: kube-guard.io
  names:
    kind: HelmScanReport
    plural: helmscanreports
    singular: helmscanreport
    listKind: HelmScanReportList
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              required: [sourceRef, findings]
              properties:
                sourceRef:
                  type: string
                  description: "Nombre del ScanRequest original"
                findings:
                  type: object
                  additionalProperties:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                        severity:
                          type: string
                        id:
                          type: string
                        error:
                          type: string
            metadata:
              type: object
      additionalPrinterColumns:
        - name: Source
          type: string
          jsonPath: .spec.sourceRef
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
