apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-guard-operator
rules:
  - apiGroups: ["kube-guard.io"]
    resources: ["scanrequests", "helmscanreports"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-guard-operator
subjects:
  - kind: ServiceAccount
    name: kube-guard-operator
    namespace: kube-guard
roleRef:
  kind: ClusterRole
  name: kube-guard-operator
  apiGroup: rbac.authorization.k8s.io
