apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-guard-operator
  namespace: kube-guard
rules:
  - apiGroups: ["kube-guard.io"]
    resources: ["scanrequests", "helmscanreports"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods", "events"]
    verbs: ["get", "list", "create"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-guard-operator
  namespace: kube-guard
subjects:
  - kind: ServiceAccount
    name: kube-guard-operator
    namespace: kube-guard
roleRef:
  kind: Role
  name: kube-guard-operator
  apiGroup: rbac.authorization.k8s.io
